# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# 安装git
RUN apk add --no-cache git

# 先创建工作目录
WORKDIR /app

# 复制package.json和pnpm-lock.yaml (如果是pnpm)
COPY package.json pnpm-lock.yaml ./

# 安装pnpm
RUN npm install -g pnpm

# 回到app目录并安装依赖
WORKDIR /app
RUN --mount=type=cache,target=/root/.pnpm-store pnpm install

# 复制源代码
COPY ./ /app

RUN npm run build

FROM node:22.12-alpine AS release

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/pnpm-lock.yaml /app/pnpm-lock.yaml

ENV NODE_ENV=production

# 安装pnpm
RUN npm install -g pnpm

RUN pnpm install --prod --ignore-scripts

ENTRYPOINT ["node", "dist/src/server/index.js"]
