# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# 安装git
RUN apk add --no-cache git

# 先创建工作目录
WORKDIR /app

# 复制package.json和package-lock.json
COPY package*.json ./

# 先修改package.json中@chatmcp/sdk依赖为npm包(或从克隆repo)
# 方法1：替换为npm包
RUN sed -i 's|"@chatmcp/sdk": "file:../typescript-sdk/",|"@chatmcp/sdk": "^1.0.0",|g' package.json || true
# 或者方法2：克隆repo（取消注释下面两行并注释掉上面的方法）
# WORKDIR /
# RUN git clone https://github.com/path/to/typescript-sdk.git || true

# 回到app目录并安装依赖
WORKDIR /app
RUN --mount=type=cache,target=/root/.npm npm install

# 复制源代码
COPY ./ /app

RUN npm run build

FROM node:22.12-alpine AS release

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

ENV NODE_ENV=production

RUN npm ci --ignore-scripts --omit-dev

ENTRYPOINT ["node", "dist/src/server/index.js"]
