# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# 安装git
RUN apk add --no-cache git

# 先创建工作目录
WORKDIR /app

# 复制package.json和package-lock.json
COPY package*.json ./

# 回到app目录并安装依赖
WORKDIR /app
RUN --mount=type=cache,target=/root/.npm npm install

# 复制源代码
COPY ./ /app

RUN npm run build

FROM node:22.12-alpine AS release

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

ENV NODE_ENV=production

RUN npm ci --ignore-scripts --omit-dev

ENTRYPOINT ["node", "dist/src/server/index.js"]
